2024-06-28 18:56:25 â€” INFO â€” Running with edr=0.15.1
2024-06-28 18:56:25 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 18:56:25 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 18:56:29 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'deps', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project']' is 3523
2024-06-28 18:56:29 â€” INFO â€” Running with dbt=1.7.0
2024-06-28 18:56:29 â€” INFO â€” Updating lock file in file path: /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project/package-lock.yml
2024-06-28 18:56:29 â€” INFO â€” Installing dbt-labs/dbt_utils
2024-06-28 18:56:29 â€” INFO â€” Installed from version 0.8.6
2024-06-28 18:56:29 â€” INFO â€” Updated version available: 1.2.0
2024-06-28 18:56:29 â€” INFO â€” Installing elementary-data/elementary
2024-06-28 18:56:29 â€” INFO â€” Installed from version 0.15.1
2024-06-28 18:56:29 â€” INFO â€” Updated version available: 0.15.2
2024-06-28 18:56:29 â€” INFO â€” 
2024-06-28 18:56:29 â€” INFO â€” Updates available for packages: ['dbt-labs/dbt_utils', 'elementary-data/elementary']                 
Update your versions in packages.yml, then run dbt deps
2024-06-28 18:56:29 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 18:56:32 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.
Encountered an error:
Runtime Error
  Could not find profile named 'elementary'[0m
2024-06-28 18:56:32 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 18:56:35 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Runtime Error
  Could not find profile named 'elementary'
2024-06-28 18:56:35 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 18:56:37 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 18:56:37 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 18:56:40 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Encountered an error:
Runtime Error
  Could not find profile named 'elementary'
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Runtime Error
  Could not find profile named 'elementary'
2024-06-28 18:57:12 â€” INFO â€” Running with edr=0.15.1
2024-06-28 18:57:12 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
[31;20m2024-06-28 18:57:15 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.
Encountered an error:
Runtime Error
  Could not find profile named 'elementary'[0m
2024-06-28 18:57:15 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
2024-06-28 18:57:18 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Runtime Error
  Could not find profile named 'elementary'
2024-06-28 18:57:18 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
2024-06-28 19:00:11 â€” INFO â€” Running with edr=0.15.1
2024-06-28 19:00:49 â€” INFO â€” Running with edr=0.15.1
2024-06-28 19:00:49 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
[31;20m2024-06-28 19:00:52 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'default'. The valid target names for this profile are:
   - elementary_dev[0m
2024-06-28 19:00:52 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
2024-06-28 19:00:55 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'default'. The valid target names for this profile are:
   - elementary_dev
2024-06-28 19:00:55 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
[31;20m2024-06-28 19:00:58 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 19:00:58 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
[31;20m2024-06-28 19:01:00 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'default'. The valid target names for this profile are:
   - elementary_dev
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'default'. The valid target names for this profile are:
   - elementary_dev
2024-06-28 19:01:25 â€” INFO â€” Running with edr=0.15.1
2024-06-28 19:01:25 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
[31;20m2024-06-28 19:01:28 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'default'. The valid target names for this profile are:
   - elementary_dev[0m
2024-06-28 19:01:28 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
2024-06-28 19:01:31 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'default'. The valid target names for this profile are:
   - elementary_dev
2024-06-28 19:01:31 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
[31;20m2024-06-28 19:01:33 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 19:01:33 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
[31;20m2024-06-28 19:01:36 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'default'. The valid target names for this profile are:
   - elementary_dev
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'default'. The valid target names for this profile are:
   - elementary_dev
2024-06-28 19:03:24 â€” INFO â€” Running with edr=0.15.1
2024-06-28 19:03:24 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:03:31 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1837
2024-06-28 19:03:31 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:03:35 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1496
2024-06-28 19:03:35 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:03:38 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1494
2024-06-28 19:03:38 â€” INFO â€” Elementary's database and schema: '"postgres.pulic_elementary"'
2024-06-28 19:03:38 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
[31;20m2024-06-28 19:03:41 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Encountered an error while running operation: Database Error
  relation "pulic_elementary.elementary_test_results" does not exist
  LINE 7:         select * from "postgres"."pulic_elementary"."element...
                                ^
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error while running operation: Database Error
  relation "pulic_elementary.elementary_test_results" does not exist
  LINE 7:         select * from "postgres"."pulic_elementary"."element...
                                ^
2024-06-28 19:04:47 â€” INFO â€” Running with edr=0.15.1
2024-06-28 19:04:47 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:04:54 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 3857
2024-06-28 19:04:54 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:04:58 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1496
2024-06-28 19:04:58 â€” INFO â€” edr (0.15.1) and Elementary's dbt package (0.15.2) are compatible.
2024-06-28 19:04:58 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:01 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1496
2024-06-28 19:05:01 â€” INFO â€” Elementary's database and schema: '"postgres.public_elementary"'
2024-06-28 19:05:01 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:04 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 63012
2024-06-28 19:05:04 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_source_freshness_results", "macro_args": {"days_back": 7, "invocations_per_test": 720}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:07 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_source_freshness_results", "macro_args": {"days_back": 7, "invocations_per_test": 720}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1440
2024-06-28 19:05:07 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models", "macro_args": {"exclude_elementary": true}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:10 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models", "macro_args": {"exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 3006
2024-06-28 19:05:10 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_sources", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:14 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_sources", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1440
2024-06-28 19:05:14 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_exposures", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:17 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_exposures", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1440
2024-06-28 19:05:17 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_singular_tests", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:20 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_singular_tests", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1440
2024-06-28 19:05:20 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_runs", "macro_args": {"days_back": 7, "exclude_elementary": true}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:23 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_runs", "macro_args": {"days_back": 7, "exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1440
2024-06-28 19:05:23 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_dbt_models_test_coverage", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:26 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_dbt_models_test_coverage", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1634
2024-06-28 19:05:26 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_nodes_depends_on_nodes", "macro_args": {"exclude_elementary": true}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:29 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_nodes_depends_on_nodes", "macro_args": {"exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 2058
2024-06-28 19:05:29 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:32 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_latest_invocation", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 8048
2024-06-28 19:05:32 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_latest_invocations_data", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:05:36 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_latest_invocations_data", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1896
2024-06-28 19:07:35 â€” INFO â€” Running with edr=0.15.1
2024-06-28 19:07:35 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:07:38 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 3510
2024-06-28 19:07:38 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:07:42 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1496
2024-06-28 19:07:42 â€” INFO â€” edr (0.15.1) and Elementary's dbt package (0.15.2) are compatible.
2024-06-28 19:07:42 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:07:45 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1496
2024-06-28 19:07:45 â€” INFO â€” Elementary's database and schema: '"postgres.public_elementary"'
2024-06-28 19:07:45 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:07:48 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 63012
2024-06-28 19:07:48 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_source_freshness_results", "macro_args": {"days_back": 7, "invocations_per_test": 720}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:07:51 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_source_freshness_results", "macro_args": {"days_back": 7, "invocations_per_test": 720}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1440
2024-06-28 19:07:51 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models", "macro_args": {"exclude_elementary": true}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:07:55 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models", "macro_args": {"exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 3006
2024-06-28 19:07:55 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_sources", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:07:58 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_sources", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1440
2024-06-28 19:07:58 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_exposures", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:08:01 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_exposures", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1440
2024-06-28 19:08:01 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_singular_tests", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:08:04 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_singular_tests", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1440
2024-06-28 19:08:04 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_runs", "macro_args": {"days_back": 7, "exclude_elementary": true}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:08:08 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_runs", "macro_args": {"days_back": 7, "exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1440
2024-06-28 19:08:08 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_dbt_models_test_coverage", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:08:11 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_dbt_models_test_coverage", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1634
2024-06-28 19:08:11 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_nodes_depends_on_nodes", "macro_args": {"exclude_elementary": true}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:08:14 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_nodes_depends_on_nodes", "macro_args": {"exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 2058
2024-06-28 19:08:14 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:08:17 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_latest_invocation", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 8048
2024-06-28 19:08:17 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_latest_invocations_data", "macro_args": {}} --project-dir /home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 19:08:20 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_latest_invocations_data", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-flask/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1896
2024-06-28 21:40:16 â€” INFO â€” Running with edr=0.15.1
2024-06-28 21:40:16 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:40:16 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 21:41:04 â€” INFO â€” Running with edr=0.15.1
2024-06-28 21:41:24 â€” INFO â€” Running with edr=0.15.1
2024-06-28 21:41:24 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:41:24 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary
2024-06-28 21:42:06 â€” INFO â€” Running with edr=0.15.1
2024-06-28 21:42:06 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:42:06 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 21:42:57 â€” INFO â€” Running with edr=0.15.1
2024-06-28 21:42:57 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:42:57 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 21:44:41 â€” INFO â€” Running with edr=0.15.1
2024-06-28 21:44:41 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:44:41 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary
2024-06-28 21:49:17 â€” INFO â€” Running with edr=0.14.1
2024-06-28 21:49:56 â€” INFO â€” Running with edr=0.14.1
2024-06-28 21:50:10 â€” INFO â€” Running with edr=0.14.1
2024-06-28 21:50:10 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:50:10 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary
2024-06-28 21:52:57 â€” INFO â€” Running with edr=0.14.1
2024-06-28 21:52:57 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:52:57 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary
2024-06-28 21:53:21 â€” INFO â€” Running with edr=0.14.1
2024-06-28 21:53:36 â€” INFO â€” Running with edr=0.14.1
2024-06-28 21:53:36 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:53:36 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary
2024-06-28 21:56:06 â€” INFO â€” Running with edr=0.14.1
2024-06-28 21:56:06 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:56:06 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary
2024-06-28 21:56:39 â€” INFO â€” Running with edr=0.15.1
2024-06-28 21:56:39 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:56:39 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary
2024-06-28 21:56:56 â€” INFO â€” Running with edr=0.15.1
2024-06-28 21:56:56 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:56:56 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 21:59:18 â€” INFO â€” Running with edr=0.15.1
2024-06-28 21:59:18 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 21:59:18 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 22:01:04 â€” INFO â€” Running with edr=0.15.1
2024-06-28 22:01:04 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:01:07 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.[0m
2024-06-28 22:01:07 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 22:01:09 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:01:09 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:01:11 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 22:01:11 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:01:15 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:01:36 â€” INFO â€” Running with edr=0.15.1
2024-06-28 22:01:36 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
[31;20m2024-06-28 22:01:38 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.[0m
2024-06-28 22:01:38 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
2024-06-28 22:01:40 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:01:40 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
[31;20m2024-06-28 22:01:42 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 22:01:42 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
[31;20m2024-06-28 22:01:44 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:02:10 â€” INFO â€” Running with edr=0.15.1
2024-06-28 22:02:17 â€” INFO â€” Running with edr=0.15.1
2024-06-28 22:02:17 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target dev
[31;20m2024-06-28 22:02:19 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.[0m
2024-06-28 22:02:19 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target dev
2024-06-28 22:02:20 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'dev']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:02:20 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target dev
[31;20m2024-06-28 22:02:22 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 22:02:22 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target dev
[31;20m2024-06-28 22:02:24 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'dev']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:04:00 â€” INFO â€” Running with edr=0.15.1
2024-06-28 22:04:00 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:04:02 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.[0m
2024-06-28 22:04:02 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 22:04:03 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:04:03 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:04:05 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 22:04:05 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:04:07 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:04:29 â€” INFO â€” Running with edr=0.15.1
2024-06-28 22:04:30 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:04:31 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.[0m
2024-06-28 22:04:31 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 22:04:33 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:04:33 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:04:35 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 22:04:35 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:04:37 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:08:28 â€” INFO â€” Running with edr=0.15.1
2024-06-28 22:08:28 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:08:30 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.[0m
2024-06-28 22:08:30 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 22:08:32 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:08:32 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:08:34 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 22:08:34 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:08:36 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:09:48 â€” INFO â€” Running with edr=0.15.1
2024-06-28 22:10:28 â€” INFO â€” Running with edr=0.15.1
2024-06-28 22:10:28 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:10:30 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.[0m
2024-06-28 22:10:30 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 22:10:32 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:10:32 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:10:34 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 22:10:34 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:10:36 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:11:51 â€” INFO â€” Running with edr=0.15.1
2024-06-28 22:11:51 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:11:53 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.[0m
2024-06-28 22:11:53 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 22:11:55 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:11:55 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:11:56 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 22:11:56 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:11:58 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:15:53 â€” INFO â€” Running with edr=0.15.1
2024-06-28 22:15:53 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:15:56 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.[0m
2024-06-28 22:15:56 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 22:15:57 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:15:57 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:15:59 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 22:15:59 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 22:16:01 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 22:19:51 â€” INFO â€” Running with edr=0.14.1
2024-06-28 22:19:51 â€” INFO â€” edr internal dbt package is not up-to-date, updating it...
2024-06-28 22:19:51 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 22:24:26 â€” INFO â€” Running with edr=0.14.1
2024-06-28 22:24:26 â€” INFO â€” edr internal dbt package is not up-to-date, updating it...
2024-06-28 22:24:26 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 22:27:02 â€” INFO â€” Running with edr=0.14.1
2024-06-28 22:27:02 â€” INFO â€” edr internal dbt package is not up-to-date, updating it...
2024-06-28 22:27:02 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 22:29:33 â€” INFO â€” Running with edr=0.14.1
2024-06-28 22:29:33 â€” INFO â€” edr internal dbt package is not up-to-date, updating it...
2024-06-28 22:29:33 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles
2024-06-28 22:41:50 â€” INFO â€” Running with edr=0.14.1
2024-06-28 22:41:50 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 22:41:50 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/dbt_new_project/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 23:14:27 â€” INFO â€” Running with edr=0.14.1
2024-06-28 23:14:28 â€” INFO â€” edr internal dbt package is not up-to-date, updating it...
2024-06-28 23:14:28 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 23:14:43 â€” INFO â€” Running with edr=0.14.1
2024-06-28 23:14:43 â€” INFO â€” edr internal dbt package is not up-to-date, updating it...
2024-06-28 23:14:43 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --target dev
2024-06-28 23:14:57 â€” INFO â€” Running with edr=0.14.1
2024-06-28 23:14:57 â€” INFO â€” edr internal dbt package is not up-to-date, updating it...
2024-06-28 23:14:57 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target dev
2024-06-28 23:29:31 â€” INFO â€” Running with edr=0.14.1
2024-06-28 23:29:31 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 23:29:33 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.[0m
2024-06-28 23:29:33 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 23:29:35 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 23:29:35 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 23:29:37 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 23:29:37 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 23:29:39 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 39, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 51, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 22, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
2024-06-28 23:31:39 â€” INFO â€” Running with edr=0.15.1
2024-06-28 23:31:39 â€” INFO â€” edr internal dbt package is not up-to-date, updating it...
2024-06-28 23:31:39 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 23:45:51 â€” INFO â€” Running with edr=0.15.1
2024-06-28 23:45:51 â€” INFO â€” Installing packages for edr internal dbt package...
2024-06-28 23:45:51 â€” INFO â€” Running dbt --log-format json deps --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 23:45:56 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'deps', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' is 3529
2024-06-28 23:45:56 â€” INFO â€” Running with dbt=1.8.3
2024-06-28 23:45:56 â€” INFO â€” Updating lock file in file path: /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project/package-lock.yml
2024-06-28 23:45:56 â€” INFO â€” Installing dbt-labs/dbt_utils
2024-06-28 23:45:56 â€” INFO â€” Installed from version 0.8.6
2024-06-28 23:45:56 â€” INFO â€” Updated version available: 1.2.0
2024-06-28 23:45:56 â€” INFO â€” Installing elementary-data/elementary
2024-06-28 23:45:56 â€” INFO â€” Installed from version 0.15.1
2024-06-28 23:45:56 â€” INFO â€” Updated version available: 0.15.2
2024-06-28 23:45:56 â€” INFO â€” 
2024-06-28 23:45:56 â€” INFO â€” Updates available for packages: ['dbt-labs/dbt_utils', 'elementary-data/elementary']                 
Update your versions in packages.yml, then run dbt deps
2024-06-28 23:45:56 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 23:45:58 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.
Encountered an error:
Runtime Error
  Could not find profile named 'elementary'[0m
2024-06-28 23:45:58 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
2024-06-28 23:46:01 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Runtime Error
  Could not find profile named 'elementary'
2024-06-28 23:46:01 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 23:46:03 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 23:46:03 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project
[31;20m2024-06-28 23:46:05 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Encountered an error:
Runtime Error
  Could not find profile named 'elementary'
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Runtime Error
  Could not find profile named 'elementary'
2024-06-28 23:46:48 â€” INFO â€” Running with edr=0.15.1
2024-06-28 23:46:48 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary
[31;20m2024-06-28 23:46:50 â€” ERROR â€” Unable to get the latest invocation: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'elementary'. The valid target names for this profile are:
   - default[0m
2024-06-28 23:46:50 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary
2024-06-28 23:46:52 â€” DEBUG â€” Could not get warehouse info.
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/data_monitoring/data_monitoring.py", line 140, in _get_warehouse_info
    self.internal_dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'elementary'. The valid target names for this profile are:
   - default
2024-06-28 23:46:52 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary
[31;20m2024-06-28 23:46:55 â€” ERROR â€” Failed to parse Elementary's database and schema.[0m
2024-06-28 23:46:55 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary
[31;20m2024-06-28 23:46:57 â€” ERROR â€” Could not generate the report - Error: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'elementary'. The valid target names for this profile are:
   - default
Please reach out to our community for help with this issue.[0m
Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 88, in _run_command
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/report/report.py", line 50, in get_report_data
    tests_api = TestsAPI(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 43, in __init__
    self.test_results_db_rows = self._get_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/api/tests/tests.py", line 55, in _get_test_results_db_rows
    return self.tests_fetcher.get_all_test_results_db_rows(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/fetchers/tests/tests.py", line 25, in get_all_test_results_db_rows
    run_operation_response = self.dbt_runner.run_operation(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 160, in run_operation
    success, command_output = self._run_command(
  File "/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/clients/dbt/dbt_runner.py", line 99, in _run_command
    raise DbtCommandError(err, command_args, logs=logs)
elementary.exceptions.exceptions.DbtCommandError: Failed to run dbt command.
Encountered an error:
Runtime Error
  The profile 'elementary' does not have a target named 'elementary'. The valid target names for this profile are:
   - default
2024-06-28 23:48:27 â€” INFO â€” Running with edr=0.15.1
2024-06-28 23:48:27 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:48:38 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 4494
2024-06-28 23:48:38 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:48:42 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1418
2024-06-28 23:48:42 â€” INFO â€” edr (0.15.1) and Elementary's dbt package (0.15.2) are compatible.
2024-06-28 23:48:42 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:48:46 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1410
2024-06-28 23:48:46 â€” INFO â€” Elementary's database and schema: '"dbt_db.dbt_schema_elementary"'
2024-06-28 23:48:46 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:48:51 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1350
2024-06-28 23:48:51 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_source_freshness_results", "macro_args": {"days_back": 7, "invocations_per_test": 720}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:48:56 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_source_freshness_results", "macro_args": {"days_back": 7, "invocations_per_test": 720}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1350
2024-06-28 23:48:56 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models", "macro_args": {"exclude_elementary": true}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:49:01 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models", "macro_args": {"exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 2924
2024-06-28 23:49:01 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_sources", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:49:05 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_sources", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1350
2024-06-28 23:49:05 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_exposures", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:49:11 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_exposures", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1350
2024-06-28 23:49:11 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_singular_tests", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:49:15 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_singular_tests", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1350
2024-06-28 23:49:15 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_runs", "macro_args": {"days_back": 7, "exclude_elementary": true}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:49:20 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_runs", "macro_args": {"days_back": 7, "exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 15922
2024-06-28 23:49:20 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_dbt_models_test_coverage", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:49:25 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_dbt_models_test_coverage", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1544
2024-06-28 23:49:25 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_nodes_depends_on_nodes", "macro_args": {"exclude_elementary": true}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:49:31 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_nodes_depends_on_nodes", "macro_args": {"exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1968
2024-06-28 23:49:31 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:49:36 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_latest_invocation", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 8414
2024-06-28 23:49:36 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_latest_invocations_data", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:49:41 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_latest_invocations_data", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 2226
2024-06-28 23:54:42 â€” INFO â€” Running with edr=0.15.1
2024-06-28 23:54:42 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:54:48 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_latest_invocation", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 3540
2024-06-28 23:54:48 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:54:52 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_adapter_type_and_unique_id", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1418
2024-06-28 23:54:52 â€” INFO â€” edr (0.15.1) and Elementary's dbt package (0.15.2) are compatible.
2024-06-28 23:54:52 â€” DEBUG â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:54:56 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_elementary_database_and_schema", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1410
2024-06-28 23:54:56 â€” INFO â€” Elementary's database and schema: '"dbt_db.dbt_schema_elementary"'
2024-06-28 23:54:56 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:55:03 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_test_results", "macro_args": {"days_back": 7, "invocations_per_test": 720, "disable_passed_test_metrics": false}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 39796
2024-06-28 23:55:03 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_source_freshness_results", "macro_args": {"days_back": 7, "invocations_per_test": 720}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:55:08 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_source_freshness_results", "macro_args": {"days_back": 7, "invocations_per_test": 720}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1350
2024-06-28 23:55:08 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models", "macro_args": {"exclude_elementary": true}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:55:14 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models", "macro_args": {"exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 2924
2024-06-28 23:55:14 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_sources", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:55:19 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_sources", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1350
2024-06-28 23:55:19 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_exposures", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:55:25 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_exposures", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1350
2024-06-28 23:55:25 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_singular_tests", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:55:31 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_singular_tests", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1350
2024-06-28 23:55:31 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_runs", "macro_args": {"days_back": 7, "exclude_elementary": true}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:55:37 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_runs", "macro_args": {"days_back": 7, "exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 15922
2024-06-28 23:55:37 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_dbt_models_test_coverage", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:55:43 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_dbt_models_test_coverage", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1544
2024-06-28 23:55:43 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_nodes_depends_on_nodes", "macro_args": {"exclude_elementary": true}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:55:49 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_nodes_depends_on_nodes", "macro_args": {"exclude_elementary": true}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 1968
2024-06-28 23:55:49 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_latest_invocation", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:55:54 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_latest_invocation", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 8414
2024-06-28 23:55:54 â€” INFO â€” Running dbt --log-format json run-operation elementary.log_macro_results --args {"macro_name": "elementary_cli.get_models_latest_invocations_data", "macro_args": {}} --project-dir /home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project --profiles-dir profiles --target elementary_dev
2024-06-28 23:56:00 â€” DEBUG â€” Result bytes size for command '['dbt', '--log-format', 'json', 'run-operation', 'elementary.log_macro_results', '--args', '{"macro_name": "elementary_cli.get_models_latest_invocations_data", "macro_args": {}}', '--project-dir', '/home/junior/projetos/venv-dbt/lib/python3.8/site-packages/elementary/monitor/dbt_project', '--profiles-dir', 'profiles', '--target', 'elementary_dev']' is 2226
